language: php

sudo: false

php:
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true

before_script:
  - composer self-update
  - composer install --prefer-dist --no-interaction
  - phpenv rehash

script:
  - vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests
  - vendor/bin/phpunit

before_install:
  - pip install --user codecov

after_success:
  - codecov

notifications:
  email: false