language: php

sudo: false

php:
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

before_script:
  - composer self-update
  - composer install --prefer-dist --no-interaction
  - phpenv rehash
  - php -S localhost:8000 -t tests &
  - sleep 3

script:
  - vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests
  - vendor/bin/phpunit --coverage-clover=clover.xml

before_install:
  - pip install --user codecov

after_success:
  - codecov

notifications:
  email: false